### ISSUE TITLE
Stuck on "EFI Volume already mounted" message when executing script PatchUSB.sh on my MacBook Pro mid-2012

### ISSUE THREAD

**Issue by shines75** [Ursinia/Mini-Monterey-Patcher#10]
Hi, Ben Sova! Thank you very much for solving the pre802.11ac patching, so that, (in theory), I can use your patcher to run macOS Monterey on my unsupported Mac...however, everytime I try to run your script "PatchUSB.sh", even if I restart my Mac, by the end, in the last steps, I get stuck with this message:
"Now installing SetVars tool...
An "EFI" volume is already mounted. Please unmount it then try again.
If you don't know what this means, then restart your Mac and try again.

EFI Volume already mounted."

Heck! What is this? I've tried to google around but I wasn't able to find a solution (by the way, no EFI volume is mounted, and this suggests that the script has a serious problem, at least on my machine)!!
I also add that my Mac runs macOS Big Sur 11.4, patched with your amazing Patched-Sur, so I supposed the NVRAM envinronment should be appropriate even for your Patched Monterey USB Installer: and in fact, despite on boot time, I don't have the "EFI Boot" icon, I've the 2nd, "Install Monterey beta"...but in this way, with the incompletely patched USB stick, I can boot through it, and everything seems to go fine, until I try to launch the macOS Installer from the menu: for some strange reason, everything crashes!!!
Help me, please, I really appreciate all your work and support to the mac community.

**Comment by shines75** [comment]
Damn'it!!! This is really weird:

matteopi@shines75 ~ % ls /Volumes                  
Crucial 2 TB				Install macOS Monterey beta		Samsung 1 TB				com.apple.TimeMachine.localsnapshots
Crucial 2 TB 1				Lavoro					Samsung 1 TB - Dati
EFI					Monterey				Windows
matteopi@shines75 ~ % umount /Volumes/EFI
umount: /Volumes/EFI: not currently mounted

Any bright ideas??

**Comment by ozziepadilla** [comment]
> Hi, Ben Sova! Thank you very much for solving the pre802.11ac patching, so that, (in theory), I can use your patcher to run macOS Monterey on my unsupported Mac...however, everytime I try to run your script "PatchUSB.sh", even if I restart my Mac, by the end, in the last steps, I get stuck with this message:
> "Now installing SetVars tool...
> An "EFI" volume is already mounted. Please unmount it then try again.
> If you don't know what this means, then restart your Mac and try again.
> 
> EFI Volume already mounted."
> 
> Heck! What is this? I've tried to google around but I wasn't able to find a solution (by the way, no EFI volume is mounted, and this suggests that the script has a serious problem, at least on my machine)!!
> I also add that my Mac runs macOS Big Sur 11.4, patched with your amazing Patched-Sur, so I supposed the NVRAM envinronment should be appropriate even for your Patched Monterey USB Installer: and in fact, despite on boot time, I don't have the "EFI Boot" icon, I've the 2nd, "Install Monterey beta"...but in this way, with the incompletely patched USB stick, I can boot through it, and everything seems to go fine, until I try to launch the macOS Installer from the menu: for some strange reason, everything crashes!!!
> Help me, please, I really appreciate all your work and support to the mac 

> Damn'it!!! This is really weird:
> 
> matteopi@shines75 ~ % ls /Volumes
> Crucial 2 TB Install macOS Monterey beta Samsung 1 TB com.apple.TimeMachine.localsnapshots
> Crucial 2 TB 1 Lavoro Samsung 1 TB - Dati
> EFI Monterey Windows
> matteopi@shines75 ~ % umount /Volumes/EFI
> umount: /Volumes/EFI: not currently mounted
> 
> Any bright ideas??

First off Ben haven’t release the new  mini Monterey patcher with the patcher adding support for the wifi for MacBook like yours at least not yet it’s still in development and second I suggest you to give some time …. And when you create the usb installer for macOS Monterey beta did you erase the usb with the right commands like that?

macOS extended journaled 
Guid partition map 

![2EAC89F0-A1AA-4FCC-9DA9-BE96755A080A](https://user-images.githubusercontent.com/78187370/125072943-448a7c80-e089-11eb-83eb-964e89c42471.jpeg)

**Comment by BenSova** [comment]
What happens if you run `rm -rf /Volumes/EFI`?
