### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by chris1111** [Ursinia/Mini-Monterey-Patcher#16]
Maybe I misunderstood ? I really dont understand why patching system for a MacBook Pro late 2013
I have this macbook and evethings work like Big Sur wit a simple OC EFI, not need patching nothings in the system, No SnapShot! No Kext installed No Hax. To Install your just need Reset Nvram; same thing for Update Monterey.
Boot from EFI USB Create Install Media Installer, reset Nvram from Gui OC, reboot to the USB and Voila
After installed put the EFI on the macSSD
<img width="1280" alt="Screen Shot 2021-07-16 at 12 11 32 PM" src="https://user-images.githubusercontent.com/6248794/125978441-78f8d7e8-eb25-4e7d-96d1-c1b3bbd63654.png">

I share with you my EFI  hope that help some other 😀
<Redacted by Ben for reasons explained in his comment>

**Comment by BenSova** [comment]
You're using OCLP, which is a completely different patcher from this. Also Late 2013 Macs don't need to patch the system, Mini Monterey or OCLP.

**Comment by chris1111** [comment]
> You're using OCLP, which is a completely different patcher from this. Also Late 2013 Macs don't need to patch the system, Mini Monterey or OCLP.

I am not using OCLP I am usig OpenCore Efi made by Me

**Comment by BenSova** [comment]
Okay, it's still a different patching method, and has nothing to do with Mini Monterey.

Also btw, sharing EFIs is not encouraged (I'm not sure why... but Mykola and co. really don't like it) so please don't share yours.

**Comment by chris1111** [comment]
> Okay, it's still a different patching method, and has nothing to do with Mini Monterey.
> 
> Also btw, sharing EFIs is not encouraged (I'm not sure why... but Mykola and co. really don't like it) so please don't share yours.

No problem its only for help other people because with this EFI you can boot Monterey and Update without issue and evethings work perfectly 
csr-active-config =00000000
