### ISSUE TITLE
Patch Usb stop at Failed to find the partition that /Volumes/Install macOS 12 Beta

### ISSUE THREAD

**Issue by fravig61** [Ursinia/Mini-Monterey-Patcher#6]
Patch Usb stop at  "Failed to find the partition that /Volumes/Install macOS 12 Beta"

**Comment by ozziepadilla** [comment]
Did you follow ben’s instructions? I have create the usb installer about three times with not errors at all

**Comment by ozziepadilla** [comment]
Make sure to type first 
sudo  /Applications/"Install macOS 12 Beta"/Contents/Resources/createinstallmedia --volume 
And one space after —volume then drag in your usb

**Comment by Monkiey** [comment]
> Patch Usb stop at "Failed to find the partition that /Volumes/Install macOS 12 Beta"

did you use the latest version of the patch which is 0.04

**Comment by fravig61** [comment]
I tried again, but always "Failed to find the partition that /Volumes/Install macOS 12 Beta is mounted from."
I follow all steps in Read me, no luck,  Why, what I wrong?

**Comment by fravig61** [comment]
no way.

Welcome to Mini Monterey's PatchUSB.sh!
This script is in alpha stages right now, but more will come in the future.
Detecting Installer USB at /Volumes/Install macOS [12/Monterey] [Beta]...
[INFO] Using Install macOS 12 Beta source.
Installer USB Detected!
Mostly unpatching if needed...
Detecting patches at script directory...
Failed to find the partition that
/Volumes/Install macOS 12 Beta
is mounted from.

**Comment by ozziepadilla** [comment]
Can you post a picture please ?

**Comment by fravig61** [comment]
single steps from new "Readme"

1) Download and extract "Source Code (zip)" from the latest release. ok
2) Open Disk Utility and format your drive as MacOS Extended (Journaled) with a GUID Partition Map. ok
3) Get the latest copy of the macOS Monterey InstallAssistant which you can find on this page (or use this Beta 2 link). ok
4) Install the package, then open Terminal and type in sudo /Applications/"Install macOS 12 Beta"/Contents/Resources/createinstallmedia --volume (make sure there's a space after --volume) then drag in your USB from your Desktop. Press enter and wait for it to finish. but the name of installed Installer is "Install macOS Monterey beta" so don't go.
5)  Drag in PatchUSB.sh then press enter and wait for it to finish.   stop as above, later I'll post a screenshot, thanks

**Comment by ozziepadilla** [comment]
Ok let’s do it like this , open finder or where you save the download of the source code it must create a folder named mini-Monterey patcher , so open that folder and keep it minimized , then  open terminal type first sudo make sure there is a space  after then open your applications folder where it’s installed install macOS 12 beta , drag it  in terminal then when it’s there use your arrow keys to get back one space then type /Contents/Resources/createinstallmedia  --volume   then drag it in your usb and press enter 

note , if you are doing copy and paste those commands  from GitHub to your terminal there doesn’t say that just type it but you can do it as I said above when drag in the install macOS 12 beta from your applications folder, I have do it four times with No errors 

if you download the source code into your iCloud Drive that not gonna work because must be downloaded locally in your downloads folder

**Comment by ozziepadilla** [comment]
When that first procedure it’s finish then drag in this file PatchUSB.sh and press enter , 

note: in all procedures it will ask for your admin Mac password

**Comment by ozziepadilla** [comment]
If all these procedures doesn’t work for you  I can send you a short video where I explain step by step how to create the usb installer

**Comment by ozziepadilla** [comment]
Chec this out the first time look how the commands looks like and look the spacers 
![F568C712-E892-408C-993D-F3CE80C3C622](https://user-images.githubusercontent.com/78187370/124354002-c5ec9580-dbd7-11eb-8440-e3f1b12a1faa.png)

**Comment by fravig61** [comment]
![Schermata 2021-07-03 alle 15 24 16](https://user-images.githubusercontent.com/2103733/124355716-f1d93c80-dc12-11eb-9751-004ad80fd7bb.png)
nothing

**Comment by fravig61** [comment]
I renamed the installer and the usb stick to "Install macOS 12 beta"but as can you see stop always at  Failed...

**Comment by ozziepadilla** [comment]
Don’t rename it, when you erase the usb leave the name like untitle and also are you using the right commands like in this picture? Of like in the second picture , if you are formatting the usb incorrectly that’s what causing the error try it again while I make a short video for you ok 
![CBA14DE3-9973-40C8-84DE-905363266687](https://user-images.githubusercontent.com/78187370/124355845-45329700-dbe1-11eb-985e-8cfb409f3195.jpeg)
![48E642FC-5507-438B-93ED-6E945DADC173](https://user-images.githubusercontent.com/78187370/124355846-4663c400-dbe1-11eb-896f-6bbff3882bc4.png)

**Comment by ozziepadilla** [comment]
The commands must be mac OS Extended Journaled and Guid partition map

**Comment by ozziepadilla** [comment]
Boths screenshots are only to show how to erase the usb correctly, don’t pay attention to the names ok

**Comment by fravig61** [comment]
ok, I'm trying

**Comment by fravig61** [comment]
without rename 
![Schermata 2021-07-03 alle 16 49 30](https://user-images.githubusercontent.com/2103733/124358046-c3615e80-dc1e-11eb-9372-1e71c1b292af.png)

**Comment by ozziepadilla** [comment]
> without rename
> ![Schermata 2021-07-03 alle 16 49 30](https://user-images.githubusercontent.com/2103733/124358046-c3615e80-dc1e-11eb-9372-1e71c1b292af.png)

I can see after --volume /volumes/ your drive name because is renamed no like this
![Screen Shot 2021-07-03 at 11 05 25 AM](https://user-images.githubusercontent.com/78187370/124358511-9eed8e00-dbee-11eb-945e-40abfac96c74.png)

**Comment by fravig61** [comment]
ok I'll format as    Untitled

**Comment by fravig61** [comment]
now its name is "Install macOS Monterey beta"

**Comment by ozziepadilla** [comment]
> now its name is "Install macOS Monterey beta"

When the process of erasing starts the name of the usb changes then starting up making disk bootable 
![image](https://user-images.githubusercontent.com/78187370/124359017-14f2f480-dbf1-11eb-91e0-4ce037151431.jpg)

**Comment by ozziepadilla** [comment]
By the way , where are you from?

**Comment by ozziepadilla** [comment]
From where did you download the installassistant pkg of macOS 12 beta ?

**Comment by fravig61** [comment]
from second link in read me

**Comment by fravig61** [comment]
http://swcdn.apple.com/content/downloads/54/23/071-59953-A_U9D4NB05NR/nqzt71pnylsuux326a4vqexb33oz0auhas/InstallAssistant.pkg

**Comment by ozziepadilla** [comment]
Ok good and it’s in your download folder right ? Then you run the pk to install macOS 12 beta.app ?

**Comment by fravig61** [comment]
yes

**Comment by fravig61** [comment]
I'm from Italy

**Comment by fravig61** [comment]
now it's copying  to disk

**Comment by ozziepadilla** [comment]
Can you check in the download folder if the installassistant pk has a number like 2 or 3

**Comment by ozziepadilla** [comment]
> now it's copying to disk

Good let it finish

**Comment by fravig61** [comment]
no, it's on external disk not mounted

**Comment by ozziepadilla** [comment]
Ok if you get the same error move the installassistant pk to your download folder

**Comment by fravig61** [comment]
no numbers just    InstallAssistant.pkg

**Comment by ozziepadilla** [comment]
> no numbers just InstallAssistant.pkg

Ok that’s good , the file must be in your local HD no in a external drive  or iCloud folders either , that’s what I know

**Comment by Monkiey** [comment]
> > no numbers just InstallAssistant.pkg
> 
> Ok that’s good , the file must be in your local HD no in a external drive or iCloud folders either , that’s what I know

Make sure you drag it out of iCloud drive if it's in there as that won't work if the file isn't locally stored.

**Comment by ozziepadilla** [comment]
I am creating the usb installer to replicate if it shows any error
![Screen Shot 2021-07-03 at 11 50 29 AM](https://user-images.githubusercontent.com/78187370/124359979-3eae1a80-dbf5-11eb-90ac-1f3f6e01bc9b.png)

**Comment by fravig61** [comment]
![Schermata 2021-07-03 alle 18 01 38](https://user-images.githubusercontent.com/2103733/124360192-c8c3a680-dc28-11eb-9a6c-7547e70e413f.png)

**Comment by fravig61** [comment]
I have to go, tomorrow I'll be here, thanks 4 your help  :-)

**Comment by BenSova** [comment]
When you do try again, make sure to use the latest version (which is https://github.com/Ursinia/Mini-Monterey-Patcher/releases/tag/v0.0.5a)

**Comment by ozziepadilla** [comment]
And do not save those files or the installer os macOS 12 in iCloud or a external drive, save them in the download folder

**Comment by BenSova** [comment]
Should be fixed with https://github.com/Ursinia/Mini-Monterey-Patcher/releases/tag/v0.0.5b

**Comment by ozziepadilla** [comment]
check this out try it  download the source code.zip again and like I said above, save everything in your HDD not iCloud no externals.
![Screen Shot 2021-07-03 at 4 13 40 PM](https://user-images.githubusercontent.com/78187370/124365968-f05f4280-dc19-11eb-8f57-f3474b21e5b7.png)

**Comment by fravig61** [comment]
OK, I  updated with new patch, many thanks to BenSova, but my iMac 14,1 is very slow, maybe it's time to change... or add an ssd...

**Comment by ozziepadilla** [comment]
> OK, I updated with new patch, many thanks to BenSova, but my iMac 14,1 is very slow, maybe it's time to change... or add an ssd...

No wait isn’t you iMac I have one of those and is faster , macOS Monterey is still in beta and very buggy you must wait for the final release and you will see if is slow or not , by the way yes an SSD make it more faster but for now is macOS Monterey the problem  , I am running macOS Big Sur and running very smoothly and I won’t upgrade it yet to Monterey

**Comment by fravig61** [comment]
Ok, I wait the final, thanks for your help

**Comment by ozziepadilla** [comment]
Yeah you should wait because it's very premature to update to macOS Monterey at this time macOS Big Sur is still in 11.4 final release and there is a 11.5 beta

**Comment by Monkiey** [comment]
> OK, I updated with new patch, many thanks to BenSova, but my iMac 14,1 is very slow, maybe it's time to change... or add an ssd...

Look yes Monterey is in beta however if you just upgraded the computer will be slow for a short period of time give some time to index as when you update even on Big Sur the Mac does some file indexing after updates, I ran Monterey on the same iMac model 14,1 and yes the boot was slow however the main os felt about the same in my experience! However I did install Monterey on a separate partition so I am not sure if my experience is the same
