### ISSUE TITLE
I have a macbookpro with hd4000 graphics card and 802.11n wifi and want to get WiFi repair

### ISSUE THREAD

**Issue by haitun001** [Ursinia/Mini-Monterey-Patcher#8]
As the title describes, through your warehouse documentation, I learned that my mac can work on macos12, but I can't get rid of the Ethernet connection. Hope you can provide some help in this regard.

**Comment by BenSova** [comment]
Wait, so what's the issue

**Comment by haitun001** [comment]
I want to find a way to repair the 802.11nwifi adapter, thank you

**Comment by BenSova** [comment]
What do you mean repair?

If you mean get it working in Monterey, I've tried, it doesn't work out.

If you mean upgrade it, google 802.11ac upgrade for your Mac. 

If you mean actually repair the card because it's broken even in Catalina and Big Sur, then just upgrade it to an 802.11ac card.

**Comment by ozziepadilla** [comment]
The way that you can have your wifi working with macOS Monterey  is replacing the wireless card which must be a 802.11ac not 802.11n it is explained here but if your wifi card on your Mac isn’t working with Catalina and Big Sur that means it’s broken 
![C143DB30-21B5-4B1F-B64F-13B87C468BE3](https://user-images.githubusercontent.com/78187370/124693325-37b13180-dead-11eb-9705-13c0618a9b54.jpeg)

**Comment by ozziepadilla** [comment]
![66FD72C6-4EAB-4EC7-8680-88F472218F93](https://user-images.githubusercontent.com/78187370/124693500-8f4f9d00-dead-11eb-9c36-486353476fbf.jpeg)

**Comment by haitun001** [comment]
Unfortunately, this model cannot be upgraded to 802.11ac wifi card. It can work very well under catalina. Under big sur, another patch can be used to make wifi work normally. I want to know if macos12 can also be repaired. Because my English ability is not good, most rely on Google Translate, please understand some expression errors. Thank you.

**Comment by ozziepadilla** [comment]
It’s ok but since macOS Big Sur drop support for few Macs then with macOS Monterey will be more , I suggest to stay with macOS Big Sur still it’s in 11.4 and very stable, 11.5 will be out soon too or if you still want to install macOS Monterey the only way it’s with the Ethernet cable connected

**Comment by BenSova** [comment]
> Under big sur, another patch can be used to make wifi work normally.

Apple changed some the IO80211FamilyLegacy.kext, and now it can't be downgraded without symbol errors. Maybe later on I'll figure it out, but for now this is how it is.

I'm going to close this issue because it's not an issue but rather a lack of support I chose.

**Comment by BenSova** [comment]
So turns out I can provide this, an update will come soon.
